version: "3.8"
services:
  auth-service:
    build: .
    ports:
      - "3003:3003"
    environment:
      DATABASE_URL: postgres://admin:admin@postgres:5432/authdb
      JWT_SECRET: your_jwt_secret
    depends_on:
      - postgres
    command:
      [
        "sh",
        "-c",
        "npx prisma generate && npx prisma migrate deploy && node server.js",
      ]

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: authdb
    volumes:
      - auth-db-data:/var/lib/postgresql/data

volumes:
  auth-db-data:
