apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
  labels:
    app: app1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app1-cont
          image: zamanehsani/app1
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_URL
              value: postgres://admin:admin@postgres:5432/app1db
